[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Ensure Prisma generates the client during build
  PRISMA_GENERATE_DATAPROXY = "true"
  # Skip Prisma's telemetry
  PRISMA_TELEMETRY_DISABLED = "1"

# Handle Prisma on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build hooks
[build.processing]
  skip_processing = false

# Environment variables for build
[context.production.environment]
  PRISMA_GENERATE_DATAPROXY = "true"
  PRISMA_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  PRISMA_GENERATE_DATAPROXY = "true"
  PRISMA_TELEMETRY_DISABLED = "1"
